### ISSUE TITLE
Change Background Color from ColorPicker Control

### ISSUE THREAD

**Issue by APFDejanTrivunovic** [Dirkster99/ColorPickerLib#11]
Hello,

Can someone help me with this topic ? I want to change the background color from transparent to a defined color from the code behind. 
![screenshot](https://github.com/Dirkster99/ColorPickerLib/assets/114060232/90205428-21df-44da-bcf3-6ac6c5497bfb)

**Comment by grizoood** [comment]
Add this : `<ResourceDictionary Source="/ColorPickerLib;component/Themes/Generic.xaml" />`
