### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by ottisj** [Dirkster99/ColorPickerLib#4]
Hi there, in fact I do not know how to add files to the repository. 
The attached file contains Czech localization, could please someone add it to the project?
Jan

[Strings.cs-CZ.zip](https://github.com/Dirkster99/ColorPickerLib/files/5504842/Strings.cs-CZ.zip)

**Comment by Dirkster99** [comment]
Hi, thanx for your contribution :-)

I have included the Czech localization in version 1.6.2 please let me know if you have any issues with this.
